arch: "armv4t"
memory_map:
  text:
    base_addr: 0x100000
    file: Tegra_X1_BootROM_Nintendo_T210.bin.bak
    permissions: r-x
    size: 0x18000
  IRAM:
    base_addr: 0x40000000
    permissions: rwx
    size: 0x40000
  # TMR
  mmio_id_1:
    base_addr: 0x60005000
    permissions: rw-
    size: 0x1000
  # CLK_RST, FLOW_CTRL 
  mmio_id_2:
    base_addr: 0x60006000
    permissions: rw-
    size: 0x2000
  # SYS_REGS
  mmio_id_3:
    base_addr: 0x6000C000
    permissions: rw-
    size: 0x1000
  # GPIO6
  mmio_id_4:
    base_addr: 0x6000D000
    permissions: rw-
    size: 0x1000
  # PP
  # GP
  mmio_id_5:
    base_addr: 0x70000000
    permissions: rw-
    size: 0x1000
  # PINMUX_AUX
  mmio_id_7:
    base_addr: 0x70003000
    permissions: rw-
    size: 0x1000
  # UARTA, UARTB
  # UARTC, UARTD, UARTE
  mmio_id_8:
    base_addr: 0x70006000
    permissions: rw-
    size: 0x1000
  # I2C
  # I2C2, I2C3
  # I2C4
  mmio_id_10:
    base_addr: 0x7000C000
    permissions: rw-
    size: 0x1000
  #  I2C5, I2C6
  mmio_id_13:
    base_addr: 0x7000D000
    permissions: rw-
    size: 0x1000
  # PMC
  mmio_id_14:
    base_addr: 0x7000E000
    permissions: rw-
    size: 0x1000
  # SE
  mmio_id_15:
    base_addr: 0x70012000
    permissions: rw-
    size: 0x2000
  # MC
  mmio_id_16:
    base_addr: 0x70019000
    permissions: rw-
    size: 0x1000
  # EMC
  mmio_id_17:
    base_addr: 0x7001B000
    permissions: rw-
    size: 0x1000
  # SATA
  mmio_id_18:
    base_addr: 0x70020000
    permissions: rw-
    size: 0x10000
  # XUSB_HOST
  mmio_id_19:
    base_addr: 0x70090000
    permissions: rw-
    size: 0xA000
  # XUSB_PADCTL
  mmio_id_20:
    base_addr: 0x7009F000
    permissions: rw-
    size: 0x1000
  # SDMMC1, SDMMC2, SDMMC3, SDMMC4
  mmio_id_21:
    base_addr: 0x700B0000
    permissions: rw-
    size: 0x1000
  # SDMMC1B
  mmio_id_22:
    base_addr: 0x700B1000
    permissions: rw-
    size: 0x1000
  # SDMMC2B
  mmio_id_23:
    base_addr: 0x700B2000
    permissions: rw-
    size: 0x1000
  # SDMMC3B
  mmio_id_24:
    base_addr: 0x700B3000
    permissions: rw-
    size: 0x1000
  # SDMMC4B
  mmio_id_25:
    base_addr: 0x700B4000
    permissions: rw-
    size: 0x1000
  # XUSB_DEV
  mmio_id_26:
    base_addr: 0x700D0000
    permissions: rw-
    size: 0xA000
  # SYSCTR0
  mmio_id_27:
    base_addr: 0x700F0000
    permissions: rw-
    size: 0x10000
  # QSPI
  mmio_id_28:
    base_addr: 0x70410000
    permissions: rw-
    size: 0x1000
  TZRAM:
    base_addr: 0x7c010000
    permissions: rwx
    size: 0x10000
  ipatch:
    base_addr: 0x6001dc00
    permissions: rw-
    size: 0x400
  exc_vectors:
    base_addr: 0x6000F000
    permissions: rw-
    size: 0x1000
  # USB
  mmio_id_29:
    base_addr: 0x7D000000
    permissions: rw-
    size: 0x2000
  rom:
    base_addr: 0x7000F800
    permissions: rw-
    size: 0x800
  # usb_buf1 and usb_buf2
  # mmio_dma_usb_buf:
  #   overlay: true
  #   base_addr: 0x40005000
    # permissions: rw-
    # size: 0x8000
  mmio_g_usbd_reqp:
    overlay: true
    base_addr: 0x40003000
    permissions: rw-
    size: 0x1000
boot:
  # A list of addresses required for a successful boot
  required:
    # An address (or symbol) in this list may indicate the if/else branch of a positive check
    - 0x00101134
    - 0x0010142A
    - 0x00102896
  # A list of addresses which indicate a failed boot
  avoid:
    # if/else branch of a failed check
    - 0x00101474
    # prepare_nvtboot_launch
    - 0x00101328
  # Address at which the firmware is considered booted (successfully or unsuccessfully based on the previous config attributes)
  target: 0x00102896
# This configuration is used to derive a firmware state which is considered to be booted successfully and continue fuzzing from here
handlers:
  sub_102CEE:
    addr: 0x102cee
    handler: fuzzware_harness.user_hooks.tegra.tegra_handlers.sub_102CEE
  rcm_send_initial_hwinfo_after_connection:
    addr: 0x102a80
    handler: fuzzware_harness.user_hooks.tegra.tegra_handlers.rcm_send_initial_hwinfo_after_connection
  delay_us:
    addr: 0x100e50
  usb_flush_ep:
    addr: 0x1071b8
  meminit_memunpack:
    addr: 0x101070
  debug_output:
    addr: 0x1022ea
  sub_114D3C:
    addr: 0x114d3c
  some_usb_charger_stuff:
    addr: 0x104282
  j_memcpy_libc:
    addr: 0x104356
    handler: fuzzware_harness.user_hooks.tegra.tegra_handlers.j_memcpy_libc
  rcm_error_and_reset_ep1:
    addr: 0x1023fc
  memset:
    addr: 0x104344
  skip_0x107848:
    addr: 0x107848
    handler: fuzzware_harness.user_hooks.tegra.tegra_handlers.skip_0x107848