arch: cortex-m
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  rom:
    base_addr: 0x8000000
    file: firmware.bin
    is_entry: true
    permissions: r-x
    size: 0x260
mmio_models:
  unmodeled:
    pc_08000156_mmio_40000000:
      access_size: 0x4
      addr: 0x40000000
      pc: 0x8000156
    pc_0800015c_mmio_40000004:
      access_size: 0x4
      addr: 0x40000004
      pc: 0x800015c
